default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Rails.application.credentials.dig(:db_username) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>
  host: <%= Rails.application.credentials.dig(:db_host) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:development, :db_database_dsv) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:test, :db_database_tst) %>